apiVersion: skaffold/v1beta5
kind: Config
build:
    artifacts:
        - image: ts-node
# test:
#     - image: ts-node
# structureTests:
#     - ./tests/*
deploy:
    kubectl:
        manifests:
            - "kubernetes/**"
