apiVersion: v1
kind: Service
metadata:
    name: ts-node-service
spec:
    ports:
        - name: http
          port: 4100
          targetPort: nodejs-port
          protocol: TCP
    selector:
        app: ts-node
    type: LoadBalancer
